name: modular_di
description: "A lightweight and flexible module system for Flutter applications, providing dependency injection and module management capabilities."
version: 0.0.5
repository: https://github.com/davidsdearaujo/modular_di

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  auto_injector: ">=2.0.5 <3.0.0"
  uuid: ">=3.0.0 <5.0.0"
  meta: ">=1.3.0 <1.17.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: